#ifndef PUMPKIN_CONSTS_H
#define PUMPKIN_CONSTS_H

enum{PUMPK_STUCK, PUMPK_FOLLOWBAT_ON_LEFT, PUMPK_FOLLOWBAT_ON_RIGHT, PUMPK_LEAVEBAT, PUMPK_FREE_FROM_POT, PUMPK_LEAVEPOT};

enum{PUMPK_RED, PUMPK_GRAY, PUMPK_BLUE, PUMPK_YELLOW, PUMPK_MAX};

#endif //PUMPKIN_CONSTS_H