#ifndef H_CONST_PLAYER_CONTROLS
#define H_CONST_PLAYER_CONTROLS

#include <cstddef>

enum{FUNC_LEFT, FUNC_RIGHT, FUNC_UP, FUNC_DOWN, FUNC_SHOOT, FUNC_WEAPSELECT, FUNC_MEGABOMB, FUNC_MAX};

enum{KEYB_LEFT, KEYB_RIGHT, KEYB_UP, KEYB_DOWN, KEYB_SHOOT, KEYB_WEAPON_SELECT, KEYB_MEGABOMB, KEYB_MAX};

enum{BTN_SHOOT, BTN_WEAPON_SELECT, BTN_MEGABOMB, BTN_MAX};

enum{DEVICE_KEYBOARD, DEVICE_JOYSTICK};

enum{JOY_MVT_HATS, JOY_MVT_AXES};

enum{ JOY_MOVE_TYPE, JOY_X_AXIS_NUM, JOY_Y_AXIS_NUM, JOY_HAT_NUM, JOY_AXIS_THRESHOLD, JOY_MAX };

constexpr std::size_t JOY_MOVE_NUM = 4;

#endif //H_CONST_PLAYER_CONTROLS