#ifndef ONE_PLAYER_RIMS_CONSTS_H
#define ONE_PLAYER_RIMS_CONSTS_H

namespace rims{

enum{ LEFT_RIMS, RIGHT_RIMS, RIM_SIDE_NUM };

enum{ RIM_NULL_STATE = -1, REMOV_1ST_RIM = 0, REMOV_2ND_RIM = 1, REMOVE_3RD_RIM = 2, RIM_MAX = 3};

enum{ RIM_IS_STATIC, RIM_GOES_DOWN, RIM_GOES_UP };

}

#endif //ONE_PLAYER_RIMS_CONSTS_H