#ifndef OPTIONS_CONTEXT_MAIN_MENU_CONSTS_H
#define OPTIONS_CONTEXT_MAIN_MENU_CONSTS_H

namespace optionsMenu{

enum{
	TXT_MAIN_MENU_TITLE,
	TXT_LANGUAGE_MENU,
	TXT_GRAPHICS_MENU,
	TXT_SOUND_MENU,
	TXT_MUSIC_MENU,
	TXT_QUIT_MENU,
	TXT_MENUS_MAX
};

enum{
	BTN_LANGUAGE,
	BTN_GRAPHICS,
	BTN_SOUNDS,
	BTN_MUSIC,
	BTN_QUIT,
	BTN_MAX
};

}

#endif //OPTIONS_CONTEXT_MAIN_MENU_CONSTS_H