#ifndef CAMPAIGN_CHOICE_CONSTS_H
#define CAMPAIGN_CHOICE_CONSTS_H

namespace campaignChoice{
	enum{ TITLE_TEXT, WITH_SHOP_TEXT, STD_CAMPAIGN_TEXT , LEVEL_TEXT, TEXT_MAX };

}

#endif //CAMPAIGN_CHOICE_CONSTS_H