#ifndef INPUT_SCREEN_CONSTS_H
#define INPUT_SCREEN_CONSTS_H

namespace duels{

enum{   TXT_TITLE, 				// = 0
		TXT_KEYBOARD, 
		TXT_JOYSTICK, 
		TXT_MOVE_TO_LEFT, 
		TXT_MOVE_TO_RIGHT, 		// = 4
		TXT_USE_BONUS, 
		TXT_ZONE_SPEC, 
		TXT_AXIS_NUM, 
		TXT_HAT_NUM, 			// = 8
		TXT_BUTTON_NUM, 
		TXT_DEVICE,
		TXT_PUSH_KEY,
		TXT_PUSH_JOYBTN,		// = 12
		TXT_AXES_COUNT,
		TXT_HATS_COUNT,
		TXT_BTNS_COUNT,
		TXT_PLUG_A_JOYSTICK,	// = 16
		TXT_SEE_JOY_INFOS,	
		TXT_BLUE_PLAYER,
		TXT_RED_PLAYER,
		TXT_MAX };				// = 18




}

#endif //INPUT_SCREEN_CONSTS_H