#ifndef DUELS_INPUTS_CONSTS_H
#define DUELS_INPUTS_CONSTS_H

namespace duels{

enum{DEVICE_KEYBOARD, DEVICE_JOYSTICK1, DEVICE_JOYSTICK2, DEVICE_MAX };

enum{JOYMOV_AXES, JOYMOV_HATS, JOYMOV_ERROR};

enum{JOY_BTN_BONUS, JOY_BTN_SPE_ZONE, JOY_BTN_MAX};

enum{INP_MOV_LEFT, INP_MOV_RIGHT, INP_ACTIVBONUS, INP_SPE_ZONE, INP_MAX};

enum{KEY_LEFT, KEY_RIGHT, KEY_ACTIVBONUS, KEY_SPE_ZONE, KEY_MAX};

}

#endif //DUELS_INPUTS_CONSTS_H