#ifndef CONSTEXPR_SCREEN_H
#define CONSTEXPR_SCREEN_H

constexpr int SQR_SIZE = 48;

constexpr int EDITOR_GRID_SQUARES_WIDTH = 20;
constexpr int EDITOR_GRID_SQUARES_HEIGHT = 15;
constexpr int EDITOR_BRICK_ELEMENTS_SQUARES_WIDTH = 6;
constexpr int EDITOR_BRICK_ELEMENTS_SQUARES_HEIGHT = 7;

constexpr int BRICK_ELEMENTS_WIDTH = EDITOR_BRICK_ELEMENTS_SQUARES_WIDTH * SQR_SIZE;
constexpr int BRICK_ELEMENTS_HEIGHT = EDITOR_BRICK_ELEMENTS_SQUARES_HEIGHT * SQR_SIZE;

constexpr int EDITOR_GRID_WIDTH = SQR_SIZE * EDITOR_GRID_SQUARES_WIDTH;
constexpr int EDITOR_GRID_HEIGHT = SQR_SIZE * EDITOR_GRID_SQUARES_HEIGHT;

constexpr int EDITOR_WINDOW_WIDTH = EDITOR_GRID_WIDTH + BRICK_ELEMENTS_WIDTH;
constexpr int EDITOR_WINDOW_HEIGHT = EDITOR_GRID_HEIGHT + SQR_SIZE * 4;

constexpr int LogWindowWidth = EDITOR_WINDOW_WIDTH;
constexpr int LogWindowHeight = 256;

#endif //CONSTEXPR_SCREEN_H