#ifndef SPRITE_MOVE_LIB_CONSTS_H
#define SPRITE_MOVE_LIB_CONSTS_H

namespace spriteMove{

enum{DESTR_PATHEND, DESTR_NORTH, DESTR_SOUTH, DESTR_WEST, DESTR_EAST, DESTR_MAX };

}

#endif //SPRITE_MOVE_LIB_CONSTS_H